### ISSUE TITLE
org-variable-pitch - How to use the default face as fixed face?

### ISSUE THREAD

**Issue by ThibautVerron** [cadadr/elisp#51] opened 2020-07-29 10:58 UTC
Hi,

The fixed face is set by the variable `org-variable-pitch-fixed-font` (family only) and the face `org-variable-pitch-face` (everything else). The family part cannot be set in the face because it is rewritten when the mode is loaded.

What is the easiest way to get ovp to use the default face for fixed space?

At the moment I have something like

```
(setq org-variable-pitch-fixed-font
  (face-attribute 'default :family))
 
(require 'org-variable-pitch)

(set-face-attribute 'org-variable-pitch-face nil
  :inherit 'default)
```
  
but it seems to cause me to lose, for example, the highlighting of source block headers.

Is there a better way to do it?

And is there a good reason why ovp, by default, uses a different font than the default monospace font?

**Comment by cadadr** [comment] 2020-07-31 18:44
The main reason we have that variable is that people might customise `default` _after_ loading OVP, so if it just inherited from `default`, it could still differ from it. Also, some people may use a non-monospaced font for `default`.

But I think that the way it behaves here is not good indeed, so I'll try to come up with something better.

In the mean time I think removing line 134

      (set-face-attribute 'org-variable-pitch-face nil :family org-variable-pitch-fixed-font)

and then in your init.el

    (set-face-attribute 'org-variable-pitch-face (face-attribute 'default :font))

could improve your situation. If you try it, can you report if it works fine and helps with your situation afterwards?

Guess obsoleting `org-variable-pitch-fixed-font`, adding an `org-variable-pitch-setup` function that syncs `org-variable-pitch-face` with `default`, and documenting how it behaves could be an improvement. Ideally I'd wish to have `org-variable-pitch-face` inherit from `default` directly, but it seems that it's not possible to inherit only part of a face's attributes, which results in the issue you have with highlights.

FWIW, this is kinda rooted in my own config, because all monospace fonts are governed by a single variable somewhere in my init.el and this issue seems to be that thing leaking into ovp.el. Sorry for the inconvenience.

**Comment by cadadr** [comment] 2020-07-31 19:56
Actually, would you mind giving [this](https://github.com/cadadr/elisp/blob/ovp-new-face-setup/org-variable-pitch.el) a try? I've set up a branch to test out a possible enhancement for this situation. If it's not clear what to do from reading the docs for [`org-variable-pitch-setup`](https://github.com/cadadr/elisp/blob/ovp-new-face-setup/org-variable-pitch.el#L168) in there, tell me here and I'll elaborate on what happens in this new version.

**Comment by ThibautVerron** [comment] 2020-08-01 12:39
Hey, thanks for the replies and the quick fix.

I had a look at the docstrings, it looks pretty intuitive and overall a reasonable solution. I will try it at work on Monday but I don't expect any surprise.

Thanks again!

>  Also, some people may use a non-monospaced font for default.

That's a good point. `fixed-pitch` would be a better choice, but we would have to check if it does the right thing for users who have only set up `default` and possibly `variable-pitch`.

**Comment by cadadr** [comment] 2020-08-01 19:15
Thank you, and you're welcome!

TIL that `fixed-pitch` exists... Maybe we introduce some logic that checks if `default` is monospace (using maybe `custom-face-state` and sth else to determine font pitch, IDK what that could be, maybe `font-info`) and use `fixed-pitch` if it's not. There's the "spc" attribute in the X font spec strings (XLFDs, I guess), but I gotta do some searching later if it's reliable.

**Comment by ThibautVerron** [comment] 2020-08-03 08:37
Hi, after testing the new branch, it looks fine. Thanks again!

It looks like `fixed-pitch` by default does not inherit from default, or vice-versa. In theory, I would say that it should be fine to use `fixed-pitch` as basis and advise users who have set only `default` (me included) to set `fixed-pitch` it to their liking. 

Intuitively, I think that a proper setup, instead of just setting `default`, is to set `fixed-pitch` and/or `variable-pitch`, and then have `default` inherit from one of those. I just changed my config for that, and it seems to work, but faces in Emacs are frequently more complicated than they look.

Fwiw, I don't think trying to automatically detect whether `default` is fixed pitch or not is worth it. If you want to support both cases, wouldn't a customizable variable, with a proper setter, be enough? Just adding a couple recognized symbol values to `org-variable-pitch-fixed-font`, for example?

**Comment by cadadr** [comment] 2020-08-26 16:29
On 2020-08-03 11:37 +03, ThibautVerron <notifications@github.com> wrote:
> Hi, after testing the new branch, it looks fine. Thanks again!

You’re welcome! Sorry it took so long to get back to you.

> It looks like `fixed-pitch` by default does not inherit from default, or vice-versa. In theory, I would say that it should be fine to use `fixed-pitch` as basis and advise users who have set only `default` (me included) to set `fixed-pitch` it to their liking.
>
> Intuitively, I think that a proper setup, instead of just setting `default`, is to set `fixed-pitch` and/or `variable-pitch`, and then have `default` inherit from one of those. I just changed my config for that, and it seems to work, but faces in Emacs are frequently more complicated than they look.

I just tried getting this to work a bit but it seems like it’s not
supposed to work because ‘default’ is apparently not meant to inherit
from anything. "(elisp) Face Attributes" says:

      Apart from the values given below, each face attribute can have
   the value ‘unspecified’.  This special value means that the face
   doesn’t specify that attribute directly.  An ‘unspecified’ attribute
   tells Emacs to refer instead to a parent face (see the description
   ‘:inherit’ attribute below); or, failing that, to an underlying face
   (*note Displaying Faces::).  The ‘default’ face must specify all
   attributes.

I’ve tried to get default to inherit from fixed-pitch in vain and it
seems to me that it only works when system default monospace coincides
with the :family of default, as an accident.  I’m not sure of the
inverse but it again seems to me that plain :inherit from default in
fixed-pitch does not seem to bind their :family together.

In any case I’m pushing a new patch to the branch. Could you just give
it a test to see if it breaks anything or not? This only syncs :family
between the faces so zoom in and out doesn’t break, and it uses the
value of org-variable-pitch-fixed-font only if it appears to be changed,
in order to not break old style setups.

I tried to :inherit directly from default or fixed-pitch but it means
_all_ values of those faces have priority and thus discoloured TODO
tags, tables, &c.

> Fwiw, I don't think trying to automatically detect whether `default` is fixed pitch or not is worth it. If you want to support both cases, wouldn't a customizable variable, with a proper setter, be enough? Just adding a couple recognized symbol values to `org-variable-pitch-fixed-font`, for example?

I think now that I’d ideally just support one and not complicate
stuff. It appears to me that as it is now, I could just get values from
default face for the default setup, and those who want to use an
alternate value could just use the alternative setup documented in
org-variable-pitch-setup’s docstring. This way it’d be backwards
compatible, require no setup for those who want to just use whatever
default looks like, and modifications to ovp fixed-face are
respected. What do you think?

Either way, if this doesn’t break yor setup and there’s nothing to fix,
I think I’ll then just ask folks on /r/emacs to see if this breaks
anything, and if not just merge the branch into the release one.

Cheers,

        -gk


--
İ. Göktuğ Kayaalp / @cadadr / <https://www.gkayaalp.com/>
pgp:   024C 30DD 597D 142B 49AC 40EB 465C D949 B101 2427

**Comment by ThibautVerron** [comment] 2020-08-27 11:09
> I’ve tried to get default to inherit from fixed-pitch in vain and it
seems to me that it only works when system default monospace coincides
with the :family of default, as an accident. 

I'm not sure of that. After noticing the discrepancy the other time I changed my settings from setting `default` to setting `fixed-pitch` and using inherit for default, and I didn't have any problem:

```
(set-face-attribute 'fixed-pitch nil :font "Inconsolata" :height 120)
(set-face-attribute 'default nil :inherit 'fixed-pitch)
```

Result of describe-face: 

```
Face: default (sample) (customize this face)

Documentation:
Basic default face.

Defined in `faces.el'.

        Family: Inconsolata
       Foundry: PfEd
         Width: normal
        Height: 120
        Weight: normal
         Slant: normal
    Foreground: #000000
    Background: white
     Underline: nil
      Overline: nil
Strike-through: nil
           Box: nil
       Inverse: nil
       Stipple: nil
          Font: #<font-object -PfEd-Inconsolata-normal-normal-normal-*-16-*-*-*-m-0-iso10646-1>
       Fontset: -PfEd-Inconsolata-normal-normal-normal-*-16-*-*-*-m-0-fontset-auto1
       Inherit: fixed-pitch
```

My system-wide monospace font is not Inconsolata, probably DejaVu Sans Mono (my DE calling it "Monospace" doesn't help)...

> I’m not sure of the
inverse but it again seems to me that plain :inherit from default in
fixed-pitch does not seem to bind their :family together.

Or do you mean that you expect that changing `fixed-pitch` after setting the inheritance should propagate to `default`? If so, then yes it does not seem to happen, instead it looks like all the properties are statically copied.

I'm not sure if it is a big problem, those fonts should be set early and not touched afterwards. 

> In any case I’m pushing a new patch to the branch. Could you just give
it a test to see if it breaks anything or not? This only syncs :family
between the faces so zoom in and out doesn’t break, and it uses the
value of org-variable-pitch-fixed-font only if it appears to be changed,
in order to not break old style setups.

I never thought of testing zooming with the old version, but it does not appear to work with the new version either.
If I don't call the setup function, `org-variable-pitch-fixed-face` is DejaVu Sans Mono and zooming works correctly (but the size is wrong even at the default zoom level.

If I do call the setup function, only the family is set, as expected:

```
Face: org-variable-pitch-fixed-face (sample) (customize this face)

Documentation:
Face for initial space and list item bullets.
This face is used to keep them in monospace when using
‘org-variable-pitch-minor-mode’.

Defined in `org-variable-pitch.el'.

        Family: Inconsolata
       Foundry: unspecified
         Width: unspecified
        Height: unspecified
        Weight: unspecified
         Slant: unspecified
    Foreground: unspecified
    Background: unspecified
     Underline: unspecified
      Overline: unspecified
Strike-through: unspecified
           Box: unspecified
       Inverse: unspecified
       Stipple: unspecified
          Font: unspecified
       Fontset: unspecified
       Inherit: unspecified

```

But zooming does not appear to change the monospace font size.

> I think now that I’d ideally just support one and not complicate
stuff. It appears to me that as it is now, I could just get values from
default face for the default setup, and those who want to use an
alternate value could just use the alternative setup documented in
org-variable-pitch-setup’s docstring. This way it’d be backwards
compatible, require no setup for those who want to just use whatever
default looks like, and modifications to ovp fixed-face are
respected. What do you think?

Yes that sounds good.

> Either way, if this doesn’t break yor setup and there’s nothing to fix,
I think I’ll then just ask folks on /r/emacs to see if this breaks
anything, and if not just merge the branch into the release one.

That also sounds like a good idea regardless. Fonts are tricky and there are too many ways of setting them.

Cheers, thanks for your work!
Thibaut

**Comment by terlar** [comment] 2020-08-27 11:27
What about:
```
(set-face-attribute 'fixed-pitch nil :family "Inconsolata")
(set-face-attribute 'default nil :inherit 'fixed-pitch :height 120)
```

I think there are caveats with zooming and setting a fixed height on a non-default face. Also `:font` sets a bunch of stuff, so I think you should prefer `:family`.

**Comment by ThibautVerron** [comment] 2020-08-27 12:11
Thanks! 

> I think there are caveats with zooming and setting a fixed height on a non-default face. 

I can't really do that because my config loops over a few fonts and chooses the first available on the system, and not all of those fonts have the same :size spec. 

So I guess that's one of the problems with setting `fixed-pitch` instead of `default`.

Another is that I was wrong earlier, re-evaluating the `(set-face-attribute ... :inherit...)` line is not enough to update `default`, everything in there is hard-set.

Anyway, for now I switched to 

```
(set-face-attribute 'default nil :family "Inconsolata" :height 120) 
```

Zooming works, but now the problem is the same as with Noto Sans earlier (my bad, it was not DejaVu): the monospace font in org buffers is smaller than everywhere on my system, and in particular smaller than the variable pitch font. And I don't think it will be a problem only on my system, different fonts have different base sizes. 

Removing the `:size` spec for `variable-pitch` also doesn't help, somehow it gets a spec of 105 even if I say nothing. Maybe a package I use is responsible for that... 
But zooming is not a problem with the variable-pitch text.

![Screenshot from 2020-08-27 14-01-43](https://user-images.githubusercontent.com/5845042/91439950-1e436000-e86e-11ea-888e-6677a08b9140.png)

Obtained with
```
(set-face-attribute 'default nil :family "Inconsolata" :height 120)
(set-face-attribute 'variable-pitch nil :family "Noto Sans") ;; corrected after the screenshot, same results
```

**Comment by terlar** [comment] 2020-08-27 15:10
Does that smaller face in the org buffer scale as well when you zoom? If that is the case there might be some face with relative height that is applied (e.g. `0.8` or similar). I remember having that issue where two faces were applied with relative size and then it applied the relative size twice so it became even smaller.

**Comment by cadadr** [comment] 2020-08-27 16:56
I think I'll try to set up a minimal isolated config and test this separately, but I am pretty sure default shouldn't be able to inherit. As per what the manual says, inheritance seems to work as a lazy delegation, i.e. when a face x inherits from face y, values are looked up when face x is drawn and are not copied, and face y's values take precedence. And manual says somewhat clearly that default may not inherit, tho not with exact wording.

> I never thought of testing zooming with the old version, but it does not appear to work with the new version either.
If I don't call the setup function, org-variable-pitch-fixed-face is DejaVu Sans Mono and zooming works correctly (but the size is wrong even at the default zoom level, I guess because my variable-pitch font has a :size specification).

My experience matches what @terlar says: when I used `(face-attribute 'default :font)` zoom didn't scale monospaced stuff, and that's why I changed it to `:family` instead. The idea with `:font` was that it'd sync weight, slant, or whatever else people might set, but that doesn't seem to be possible. And in second thought it's possible to want to have e.g. TODO keywords bold but say tables and code examples regular, so that'd be a bit far reaching anyways.

From the screenshot @ThibautVerron posted, your themse appears to be Leuven, which touches font height settings particularly in Org mode. Might it be interfering? Could you try disabling it and report it's effect?

`:size` shouldn't matter, I have it set, manually, for my `'default` and `'variable-pitch`, and scaling works as expected for me. It ought to be something else.

In any case after you reply as I said I'll try to come up with a canned config for testing and maybe test on a couple VMs and fresh user accounts (FWIW I use Linux Mint 20 on my device). I did post to Reddit and Mastodon but so far all I've received is a bunch of upvotes, unless @terlar came through either of that. Maybe I shoud ask `emacs-{help,devel,???}`?

You're welcome and thanks a lot to both of you for your willingness to help debug this!

---

@ThibautVerron would you mind running the following commands to verify or disprove the above?

```
$ emacs -Q --eval "(progn
(message \"Default face's default family: %S\" (face-attribute 'default :family))
(set-face-attribute 'fixed-pitch nil :family \"Liberation Serif\") ; an unlikely value for family of default
(set-face-attribute 'default nil :inherit 'fixed-pitch)
(message \"default: %S ; fixed-pitch: %S\"
  (face-attribute 'default :family)
  (face-attribute 'fixed-pitch :family))
(switch-to-buffer \"*Messages*\"))"
```

On my system after running this the `*Messages*` buffer reads as such:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Default face’s default family: "DejaVu Sans Mono"
default: "DejaVu Sans Mono" ; fixed-pitch: "Liberation Serif"
```

Could you also run the following command

```
fc-pattern -dc 'Monospace'
```

On my system this outputs

```
Pattern has 26 elts (size 32)
	family: "DejaVu Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "DejaVu Sans Mono"(w) "Bitstream Vera Sans Mono"(w) "Inconsolata"(w) "Andale Mono"(w) "Courier New"(w) "Cumberland AMT"(w) "Luxi Mono"(w) "Nimbus Mono L"(w) "Nimbus Mono PS"(w) "Nimbus Mono"(w) "Nimbus Mono PS"(w) "Nimbus Mono PS"(w) "Courier"(w) "Nimbus Mono PS"(w) "Nimbus Mono"(w) "Nimbus Mono L"(w) "Nimbus Mono PS"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgMono"(w) "Khmer OS System"(w) "Miriam Mono"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "MS Gothic"(w) "UmePlus Gothic"(w) "NSimSun"(w) "MingLiu"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung Mono"(w) "HanyiSong"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ZYSong18030"(w) "NanumGothicCoding"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgTypewriter"(w) "TlwgMono"(w) "Hasida"(w) "Mitra Mono"(w) "GF Zemen Unicode"(w) "Hapax Berbère"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeMono"(w) "Monospace"(s) "Terafik"(w) "monospace"(w) "monospace"(w) "Courier"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w)
	familylang: "en"(s) "en-us"(w)
	stylelang: "en"(s) "en-us"(w)
	fullnamelang: "en"(s) "en-us"(w)
	slant: 0(i)(s)
	weight: 80(i)(s)
	width: 100(i)(s)
	size: 12(f)(s)
	pixelsize: 12,5(f)(s)
	antialias: True(w)
	hintstyle: 1(i)(w)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	dpi: 75(f)(s)
	scale: 1(f)(s)
	lang: "en"(w)
	fontversion: 2147483647(i)(s)
	embeddedbitmap: True(s)
	decorative: False(s)
	lcdfilter: 1(i)(w)
	namelang: "en"(s)
	prgname: "fc-pattern"(s)
	symbol: False(s)
	variable: False(s)

```

**Comment by cadadr** [comment] 2020-08-27 17:08
FWIW I just tried setting my theme to Leuven and zoom does work so it ought to be something else it seems. I'm also interested in your answer to @terlar 's second comment, so long as stuff does scale with zoom, there's no problem, and it'll just require adjusting heights if you want monospace bits and variable pitch bits be the same height. I use DejaVu Mono and Sans respectively, and heights I need are 105 and 120, again, respectively (FWIW, I like DejaVu fonts because they support a huge portion of Unicode, but characters are very large especially with Mono variant which is not something I really like...)

**Comment by terlar** [comment] 2020-08-27 18:32
@cadadr Yes and no, I did come from the Reddit thread, but I am also a follower of your repository so would come here sooner or later anyways. I will try to take this for a spin and see if it changes anything. I am using the older released package and these things are working well for me already but I will see if there is any regression and if I can use the default instead of setting the `org-variable-pitch-fixed-font` explicitly.

Regarding the face I remember I had an issue where I had a relative size like `0.75` for `org-code` and `org-block` or something similar and then those places who had both these faces applied became even smaller as it applied them in order and you got 0.75 of 0.75. I can't think of any other way that font can display smaller.

Another interesting thing that might be nice, and perhaps you have some mode that does the opposite. I have a minor-mode that I call readability that applies a face to the whole buffer and then I can adjust the size for the whole buffer. I do this in org-mode buffers for example.

You can for example use this, to apply a custom face to all the fixed-pitch faces:
```
(face-remap-add-relative 'fixed-pitch 'readable-fixed-pitch)
```


My mode is here:
https://github.com/terlar/emacs-config/blob/6a09796fd62602b0a2a7ef3dcdd3557358a024ea/lisp/readable.el

I configure it like:
```emacs-lisp
(set-face-attribute 'readable-variable-pitch nil :family "Noto Serif" :height 1.1)
```

When I enable the mode `(readable-mode 1)`. All my variable pitch faces will be 10% bigger while the fixed-pitch will be untouched. Of course the reverse is possible by adjusting the `readable-fixed-pitch` face.

Hope this information is useful in some way.

**Comment by ThibautVerron** [comment] 2020-08-28 08:40
A lot to answer. `:)`

> Does that smaller face in the org buffer scale as well when you zoom?

Yes it does.

> If that is the case there might be some face with relative height that is applied (e.g. 0.8 or similar). I remember having that issue where two faces were applied with relative size and then it applied the relative size twice so it became even smaller.

I'm not familiar with that. How would I investigate it?

> From the screenshot @ThibautVerron posted, your themse appears to be Leuven, which touches font height settings particularly in Org mode. Might it be interfering? Could you try disabling it and report it's effect?

The theme is modus-operandi. The same effect appears if I disable it.

> `emacs -Q --eval "..."`

```
Default face’s default family: "DejaVu Sans Mono"
default: "DejaVu Sans Mono" ; fixed-pitch: "Liberation Serif"
```

> `fc-pattern -dc 'Monospace'`

```
Pattern has 25 elts (size 32)
        family: "DejaVu Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "Bitstream Vera Sans Mono"(w) "DejaVu Sans Mono"(w) "Inconsolata"(w) "Andale Mono"(w) "Courier New"(w) "Cumberland AMT"(w) "Luxi Mono"(w) "Nimbus Mono L"(w) "Nimbus Mono"(w) "Nimbus Mono PS"(w) "Courier"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgMono"(w) "Khmer OS System"(w) "Miriam Mono"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "MS Gothic"(w) "UmePlus Gothic"(w) "NSimSun"(w) "MingLiu"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung Mono"(w) "HanyiSong"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ZYSong18030"(w) "NanumGothicCoding"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgTypewriter"(w) "TlwgMono"(w) "Hasida"(w) "Mitra Mono"(w) "GF Zemen Unicode"(w) "Hapax Berbère"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeMono"(w) "Monospace"(s) "Terafik"(w) "monospace"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "sans-serif"(w)
        familylang: "en"(s) "en-us"(w)
        stylelang: "en"(s) "en-us"(w)
        fullnamelang: "en"(s) "en-us"(w)
        slant: 0(i)(s)
        weight: 80(i)(s)
        width: 100(i)(s)
        size: 12(f)(s)
        pixelsize: 12.5(f)(s)
        hintstyle: 1(i)(w)
        hinting: True(s)
        verticallayout: False(s)
        autohint: False(s)
        globaladvance: True(s)
        dpi: 75(f)(s)
        scale: 1(f)(s)
        lang: "en"(w)
        fontversion: 2147483647(i)(s)
        embeddedbitmap: True(s)
        decorative: False(s)
        lcdfilter: 1(i)(w)
        namelang: "en"(s)
        prgname: "fc-pattern"(s)
        symbol: False(s)
        variable: False(s)
```

---

To be clear, I have two different situations which I can reproduce:

 1. If I set size in fixed-pitch and inherit in default, the size is correct in org but monospace fragments don't scale up when zooming.
 2. If I set everything in default, the size is off in org, but everything scales correctly.

To me scenario 2 makes sense: given that org-variable-pitch only copies the family into its fixed face, there is no reason why the size should be propagated as well, right?

But I don't understand why the size is correct in scenario 1, or why the zooming does not work there.

I will try setting the size using relative height instead of fixed height.

**Comment by ThibautVerron** [comment] 2020-08-28 09:04
The following file, evaluated in `emacs -Q`, exhibits the problem:

```
(setq user-emacs-directory "/tmp/emacs")

;; Straight for fetching the package
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
	       user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package
 '(org-variable-pitch
   :type git :host github :repo "cadadr/elisp"
   :branch "ovp-new-face-setup"
   :files ("org-variable-pitch.el")))

(set-face-attribute 'default nil :family "Liberation Mono")
(set-face-attribute 'variable-pitch nil :family "DejaVu Sans")

(add-hook 'org-mode-hook
	  (defun tv/ovp-setup ()
	    (org-variable-pitch-setup)
	    (org-variable-pitch-minor-mode)))
```

Then in an org buffer, type `T =T=`.

**Comment by terlar** [comment] 2020-08-28 09:04
In scenario 2 it should also have the height (size) from the default since all faces gets its height from the default face unless overridden. So something must be manipulating that. If you inspect the face of the `=and monospace=` what does it say? For me that would be `org-verbatim` and I guess it should be for you as well. If I inspect that face it says `unspecified` for everything except Family.

Regarding scenario 1, if you set a fixed (non-relative) height for a face that will always be that size and won't allow you to zoom, only the default face can set a fixed height and that will be used as base for all other faces.

**Comment by ThibautVerron** [comment] 2020-08-28 09:06
It is `org-verbatim`, everything is unspecified except `:inherit 'shadow`.

I posted a minimal example above, even without a height specification it happens.

**Comment by terlar** [comment] 2020-08-28 09:09
Interesting, might be a difference of Emacs version?
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)
```

I don't have time now, but I will try your emacs -Q thing to see how it turns out.

**Comment by ThibautVerron** [comment] 2020-08-28 09:10
26.3 here. Apparently I can get different sizes with the minimal example provided if I set a relative size for variable-pitch, provided that I restart emacs every time. I will try to narrow the problem from there.

**Comment by cadadr** [comment] 2020-08-30 19:27
So having given this whole thing a re-read today I think this secondary issue of height mismatch is indeed expected because of variance in the base heights of fonts. Looking back to my own config, I indeed have different heights set for variable pitch and fixed pitch too.

> I suspect that the base font in variable-pitch-mode is variable-pitch instead of default, and that's what is used as a reference size...

I think this is indeed the case because when I `C-u C-x =` in an Org mode buffer both on variable pitch and fixed pitch text I get

```
[...]
    ftcrhb:-PfEd-DejaVu Sans-normal-normal-semicondensed-*-16-*-*-*-*-0-iso10646-1 (#x03)
[...]
```

which is different from what I get e.g. in `*scratch*`:

```
[...]
    ftcrhb:-PfEd-DejaVu Sans-normal-normal-semicondensed-*-14-*-*-*-*-0-iso10646-1 (#x03)
[...]
```

and if I modify `:height` of `variable-pitch` (120) to match that of `default` (105), indeed, the fonspec of variable pitch stuff matches that of default, i.e. the second excerpt.

IMO at this point if there's something OVP can or should do about this, we're maybe better off starting a separate issue for it, and close this one with a merge. What do you think?

**Comment by terlar** [comment] 2020-08-30 19:39
Yeah, that is fine by me, I did run this branch since that day and tried without setting `org-variable-pitch-fixed-font` and it seems to work, i.e. haven't noticed any difference

**Comment by ThibautVerron** [comment] 2020-08-30 20:02
Maybe before merging, you can add an optional parameter to `org-variable-pitch-setup`, to make it match all the parameters of the font? That's how it worked in the previous version of the branch (if I understand correctly), and while it was breaking zoom, at least the fonts looked correct at the default scale.

**Comment by cadadr** [comment] 2020-08-31 23:15
@terlar Thanks for your help! Much appreciated.

@ThibautVerron I think that's best achieved, for now at least, either with an advice to `org-variable-pitch-setup`, or more simply through the manual setup documented in that function's docstring. For the advice, you could go with something like:

```elisp
(define-advice org-variable-pitch-setup
    (:after (&rest _) font-not-family)
  "Use all of ‘:font’ from ‘default’ instead of only ‘:family’."
  (set-face-attribute 'org-variable-pitch-fixed-face nil
                      :font (face-attribute 'default :font)))
```

and for the custom setup, you could adapt the following

```elisp
;; Use all of ‘:font’ from ‘default’ instead of only ‘:family’.
(set-face-attribute 'org-variable-pitch-fixed-face nil
                    :font (face-attribute 'default :font))

;; Enable OVP. Don’t use ‘org-variable-pitch-setup’ with this, as it
;; may override this definition.
(add-hook 'org-mode-hook #'org-variable-pitch-minor-mode)
```

I didn't test these; if you can't get the one you prefer to work, just write here and I can help. The advice has the benefit that if `org-variable-pitch-setup` somehow changes in the future, you probably wouldn't need to update your setup. I think this is better aesthetically as a user customisation than a flag inside the program itself, given it's a special case and a trade off (break zoom vs. fonts). But before merging I'll update the docs to mention this situation.

I've created a new issue, #52, to collect more info on the font size discrepancy problem. I'll be updating the commentary section of the module and merging this branch soon, and close this issue when that's done. Thanks a lot for both of yours help!

**Comment by terlar** [comment] 2020-09-01 04:02
You are welcome, and thank you for continuing to improve this package.

Regarding font sizes, this might be of interest:
https://www.reddit.com/r/emacs/comments/ih7bon/setting_up_fonts_in_emacs_is_the_single_most/

In the discussion there I saw that you can provide a function as the font height. That might be a work-around (assuming that works with scaling). Perhaps the height property could be transformed from a fixed one to relative somehow in order to allow different sizes but still allow zooming. I will investigate this and provide info in the other issue if I find something.

**Comment by ThibautVerron** [comment] 2020-09-01 08:56
@cadadr Thanks! It somewhat feels like getting back to square 1, but at least now the face customization is grouped together.

> I think this is better aesthetically as a user customisation than a flag inside the program itself, given it's a special case and a trade off (break zoom vs. fonts).

Given that the whole point of the bug reports was to make the fixed-pitch face in org match the one everywhere else, I wouldn't consider it a special case. `;)`

That's not to say that separating the discussions is a bad idea. I really didn't expect that this bug report would hide such a can of worms, sorry.

**Comment by terlar** [comment] 2020-09-01 09:48
The reason why you see this behavior is due to how `variable-pitch-mode` works, when enable it pairs the face `variable-pitch` with `default`. It is using the `buffer-face-mode` under the hood given the face `variable-pitch`.

```
(define-minor-mode buffer-face-mode
  "Minor mode for a buffer-specific default face.

When enabled, the face specified by the variable
`buffer-face-mode-face' is used to display the buffer text."
  :lighter " BufFace"
  (when buffer-face-mode-remapping
    (face-remap-remove-relative buffer-face-mode-remapping))
  (setq buffer-face-mode-remapping
	(and buffer-face-mode
	     (face-remap-add-relative 'default buffer-face-mode-face)))
  (force-window-update (current-buffer)))
```

**Comment by cadadr** [comment] 2020-09-02 00:07
> Given that the whole point of the bug reports was to make the fixed-pitch face in org match the one everywhere else, I wouldn't consider it a special case. ;)

Sorry that y'all have to make do with such a confused maintainer :facepalm: :laughing: But to my credit I _did_ fix _something_...

> That's not to say that separating the discussions is a bad idea, but I consider the other bug to be related to zooming when variable-pitch has a set size, rather than to matching the sizes. Anyway, I really didn't expect that this bug report would hide such a can of worms, sorry about that !

No problem! To an extent OVP is an ugly hack anyways, so no surprise that we end up having different intentions than Emacs itself. Think I should maybe read up on faces a bit when I have time and maybe we can find a way to fix this without breaking things, maybe through a custom `variable-pitch-mode` (tho I'm getting ahead of myself, must read manuals before coming up with ideas at this point).

FWIW, I did intend #52 to include non-zoom size discrepancy case too, and thought a separate bug could be helpful given while matching `:family` is easier, `:height` seems to be more involved than just copying a value, even if it worked. If that's unclear, I can modify the issue text to reflect that.

**Comment by cadadr** [comment] 2020-09-11 14:04
I've updated the documentation and merged the branch into devel and devel to master, so the changes are released now. Thank you for your report and help.

I'm closing this issue now. If you experience any problems, please comment here and I'll reopen.

**Closed by cadadr** 2020-09-11 14:04 UTC
Labels: enhancement, org-variable-pitch.el
