### ISSUE TITLE
When units are 'us', C should print F instead

### ISSUE THREAD

**Issue by christoofar** [cadadr/elisp#27] opened 2017-09-25 18:38 UTC
The integer values are correct when us units are being sent, however the labels still have "C" for the degrees.  This makes things appear VERY hot. :-)

![image](https://user-images.githubusercontent.com/5059144/30824893-1018c546-a1ff-11e7-8636-2931465aab2c.png)

**Comment by cadadr** [comment] 2017-09-29 15:44
Hi Christopher, sorry for the latency.  I've tried to reproduce the
issue copying your setup (see the snippet below), but I could not, I got
‘F’ in the labels.

    (setf forecast-units 'us
          calendar-latitude 39.978636
          calendar-longitude -75.122030)

If you recently updated emacs, recompiling forecast.el may help.  If the
issue persists, report here again, including your setup for forecast.el.

**Comment by cadadr** [comment] 2017-11-09 19:42
It's been a while wihout any updates on this bug, and as I can't reproduce I'm closing this.  Feel free to open it again (if that's possible, or create a new one) in case the problem persists.

**Closed by cadadr** 2017-11-09 19:42 UTC
Labels: forecast.el
